name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # 根据项目需要设置 Node.js 版本

    - name: Install dependencies
      run: yarn install

    # Run the structure generation script
    - name: Run the structure generation script
      run: node scripts/generateStructure.cjs

    - name: Build the project
      run: yarn build --logLevel=info  # 启用详细日志

    - name: Deploy to GitHub Pages
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist  # 构建输出的目录